json_ex = {
    "age": 20,
    "eyeColor": "green",
    "name": "Liliana Gordon",
    "speed": 1,
    "battery": 1,
    "ID": "SGML",
    "SortAs": "SGML",
    "GlossTerm": "Standard",
    "Acronym": "SGML",
    "Abbrev": "ISO 8879:1986",
    "age1": 20,
    "eyeColor1": "green",
    "name1": "Liliana Gordon",
    "speed1": 1,
    "battery1": 1,
    "ID1": "SGML",
    "SortAs1": "SGML",
    "GlossTerm1": "Standard",
    "Acronym1": "SGML",
    "Abbrev1": "ISO 8879:1986",
    "age2": 20,
    "eyeColor2": "green",
    "name2": "Liliana Gordon",
    "speed2": 1,
    "battery2": 1,
    "ID2": "SGML",
    "SortAs2": "SGML",
    "GlossTerm2": "Standard",
    "Acronym2": "SGML",
    "Abbrev2": "ISO 8879:1986",
  }