<HeaderLarge@Label>:
    text_size: root.width, None
    size: self.texture_size
    size_hint: 1, None
    halign: 'right'
    color: [1,1,1,1]
    font_name: 'Inconsolata'
    bold: True
    font_size: '24pt'
<ValueLarge@Label>:
    text_size: root.width, None
    size: self.texture_size
    size_hint: 1, None
    halign: 'right'
    color: [.8,.8,.8,1]
    font_size: '48pt'
    font_name: "SourceSansPro"
<DescriptionLarge@Label>:
    text_size: root.width, None
    size: self.texture_size
    size_hint: 1, None
    halign: 'right'
    color: [.42,.42,.42, 1]
    font_name: 'Inconsolata'
    bold: True
    font_size: '24pt'
<HeaderMedium@Label>:
    text_size: root.width, None
    size: self.texture_size
    size_hint: 1, None
    halign: 'left'
    font_size: ''
    color: [1,1,1,1]
    font_name: 'Inconsolata'
    bold: True
    font_size: '24pt'
<ValueMedium@Label>:
    text_size: root.width, None
    size: self.texture_size
    size_hint: 1, None
    halign: 'left'
    color: [.8,.8,.8,1]
    font_size: '32pt'
    font_name: "SourceSansPro"

<DescriptionMedium@Label>:
    text_size: root.width, None
    size: self.texture_size
    size_hint: 1, None
    halign: 'left'
    color: [.42,.42,.42, 1]
    font_name: 'Inconsolata'
    bold: True
    font_size: '18pt'

<ValueSmall@Label>:
    text_size: root.width, None
    size: self.texture_size
    size_hint: 1, None
    halign: 'left'
    color: [.8,.8,.8,1]
    font_size: '20pt'
    font_name: "SourceSansPro"
<DescriptionSmall@Label>:
    text_size: root.width, None
    size: self.texture_size
    size_hint: 1, None
    halign: 'left'
    color: [.42,.42,.42, 1]
    font_name: 'Inconsolata'
    bold: True
    font_size: '15pt'



<SeparatorY@Widget>
    padding: [0,0,75,0]
    size_hint_x: None
    thickness: 2
    margin: 2
    width: self.thickness + 2 * self.margin
    color: [1,1,1,1]
    canvas:
        Color:
            rgb: self.color
        Rectangle:
            pos: self.x, self.height * .10 /2
            size:  self.thickness, self.height*.90
<SeparatorX@Widget>
    size_hint_y: None
    thickness: 2
    margin: 20
    height: self.thickness * self.margin
    color: [1,1,1,1]
    canvas:
        Color:
            rgb: self.color
        Rectangle:
            pos: self.x , self.y + self.margin
            size: self.width, self.thickness
<DevScreen>:
    GridLayout:
        cols: 5
        rows: 1
        BoxLayout:
            orientation: 'vertical'
            padding: [0,0,35,0]
            HeaderLarge:
                text: 'MAIN'
            ValueLarge:
                text: str(root.list['motConVehicleVelocity']) + ' mph'
            DescriptionLarge:
                text: 'SPEED'
            ValueLarge:
                text: str(root.list['batteryPackInstantaneousVoltage'])+ ' v'
            DescriptionLarge:
                text: 'BATTERY VOLT.'
            ValueLarge:
                text: str(root.list['netPower']) + " W"
            DescriptionLarge:
                text: 'NET POWER'
            Widget:
        SeparatorY:
        BoxLayout:
            orientation: 'vertical'
            padding: [35,0,35,0]
            HeaderMedium:
                text: 'CELLS'
            ValueMedium:
                text: str(root.list['highestCellTemperature']) + ' °C'
            DescriptionMedium:
                text: 'HI-CELL TEMP'
            ValueMedium:
                text: str(root.list['bpsHighVoltage']) + ' v'
            DescriptionMedium:
                text: 'HI-CELL VOLTAGE'
            SeparatorX:
            HeaderMedium:
                text: 'ARRAY'
            ValueMedium:
                text: str(root.list['mpptTotalNetPower']) + " W"
            DescriptionMedium:
                text: 'TOTAL ARRAY POWER'
            GridLayout:
                padding: [0,20,0,0]
                cols: 3
                rows: 2
                ValueSmall:
                    text: str(root.list['mppt1UnitTemperature'])
                ValueSmall:
                    text: str(root.list['mppt2UnitTemperature'])
                ValueSmall:
                    text: str(root.list['mppt3UnitTemperature'])
                DescriptionSmall:
                    text: 'SUB-A'
                DescriptionSmall:
                    text: 'SUB-B'
                DescriptionSmall:
                    text: 'SUB-C'
        SeparatorY:
        BoxLayout:
            orientation: 'vertical'
            padding: [35,0,35,0]
            HeaderMedium:
                text: 'ODOMETER'
                halign: 'left'
            ValueMedium:
                text: str(root.list['motConOdometer']) + " mi"
                halign: 'left'
            DescriptionMedium:
                text: 'TOTAL'
                line_height: 1
                halign: 'left'
            ValueMedium:
                text: "-- mi"
                halign: 'left'
            DescriptionMedium:
                text: 'TRIP'
                line_height: 1
                halign: 'left'
            SeparatorX:
            HeaderMedium:
                text: 'BPS'
                halign: 'left'
            ValueMedium:
                text: str(root.list['internalBPSTemperature']) + " °C"
                halign: 'left'
            DescriptionMedium:
                text: 'AVG. BATTERY TEMP'
                line_height: 1
                halign: 'left'
            ValueMedium:
                text: "----- --"
                halign: 'left'
            DescriptionMedium:
                text: 'STATUS'
                halign: 'left'
                line_height: 1
            Widget: